### PR TITLE
created inital template for dean martin's website

### PR DESCRIPTION
**Pull request by bstoudt01**
created new html, css, images folder & files for the Dean Martin Website

### CODE REVIEW

**Comment by lotusfleur01** [comment]
looks great!😁merge away

**Review by nickglovdev — APPROVED** [review]
The template looks good to me.

**Comment by ghost** [comment]
Looks amazing

**Review by lotusfleur01 — APPROVED** [review]
looks great merge away

**Review by ghost — APPROVED** [review]
I love it

**Pull request merged**
